### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by tudang** [frenetic-lang/ocaml-topology#58]
I checkout the latest version and then compiling has the error below. Note: The ocaml-packet is compiled with version v0.4.0

File "lib/Network.ml", line 434, characters 45-47:
Error: Signature mismatch:
       ...
       The type `label' is required but not provided
Command exited with code 2.

**Comment by arjunguha** [comment]
Hi tudang, we are in the middle of a release and updating packet, openflow, topology, and frenetic.

Once this commit is through, you'll be able to get it off OPAM:

https://github.com/ocaml/opam-repository/pull/3502

But, it looks like you know what you're doing, since you have packet pinned...

Have you updated ocamlgraph to 1.8.6?

**Comment by tudang** [comment]
Hi, I update Opam to version 1.2.0 and switch OCaml to 4.02.1. Everything can compile now.
